[versions]
activityKtx = "1.9.0"
dagger = "2.25.4"
daggerAndroid = "2.23.2"
daggerCompiler = "2.25.2"
espressoCore = "3.2.0"
hiltAndroidCompiler = "2.28-alpha"
junit = "4.12"
junitVersion = "1.1.1"
kotlin = "1.9.0"
appCompat = "1.6.1"
ktx = "1.13.1"
constrainLayout = "2.1.4"
material = "1.12.0"
room = "2.6.1"
coroutines = "1.8.0"
lifecycle = "2.8.0"
navigation = "2.7.7"
glide = "4.11.0"
maps = "18.2.0"
location = "21.2.0"
timber = "4.7.1"

[libraries]
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-android = { module = "com.google.dagger:dagger-android", version.ref = "daggerAndroid" }
dagger-android-processor = { module = "com.google.dagger:dagger-android-processor", version.ref = "daggerAndroid" }
dagger-android-support = { module = "com.google.dagger:dagger-android-support", version.ref = "daggerAndroid" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "daggerCompiler" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroidCompiler" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompiler" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
androidx-constrainLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constrainLayout" }
material = { module = "com.google.android.material:material", version.ref = "material" }
room_runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room_ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room_compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
google-play-service-location = { module = "com.google.android.gms:play-services-location", version.ref = "location"}
google-play-service-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "maps"}
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber"}

[bundles]
room = ["room.runtime", "room.ktx"]
corouitines = ["coroutines.android", "coroutines.core"]
androidx-lifecycle = ["lifecycle.runtime", "lifecycle.viewmodel"]
androidx-navigation = ["navigation.fragment", "navigation.ui"]
location = ["google.play.service.location", "google.play.service.maps"]

[plugins]
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }


