[versions]
koltin = "1.7.10"
appCompat = "1.1.0"
ktx = "1.2.0"
constrainLayout = "1.1.3"
material = "1.2.0-alpha06"
room = "2.4.3"
coroutines = "1.6.4"
lifecycle = "2.5.1"
navigation = "2.2.2"
glide = "4.11.0"
maps = "17.0.0"
timber = "4.7.1"

[libraries]
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "koltin" }
androidx-constrainLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constrainLayout" }
material = { module = "com.google.android.material:material", version.ref = "material" }
room_runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room_ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room_compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
google-play-service-location = { module = "com.google.android.gms:play-services-location", version.ref = "maps"}
google-play-service-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "maps"}
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber"}

[bundles]
room = ["room.runtime", "room.ktx"]
corouitines = ["coroutines.android", "coroutines.core"]
androidx-lifecycle = ["lifecycle.runtime", "lifecycle.viewmodel"]
androidx-navigation = ["navigation.fragment", "navigation.ui"]
location = ["google.play.service.location", "google.play.service.maps"]


