name: Publish Release

permissions:
  contents: write

env:
  # The name of the main module repository
  main_project_module: app

on:
  # Triggers the workflow on push or pull request events but only for default and protected branches
  push:
    #branches: [ "main" ]
    tags:
     - "*.*"
  #pull_request:
    #branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
 apk:
   name: Generate APK
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v6
     - name: Setup JDK
       uses: actions/setup-java@v5
       with:
         distribution: temurin
         java-version: "17"
     - name: Setup Gradle
       uses: gradle/actions/setup-gradle@v5
     - name: Setup Android SDK
       uses: android-actions/setup-android@v3
     - name: Install Android SDK packages
       run: sdkmanager "platforms;android-36" "build-tools;36.0.0"
     - name: Set execution flag for gradlew
       run: chmod +x gradlew
     - name: Build APK
       run: ./gradlew :app:assembleDebug --stacktrace
     - name: Upload APK
       uses: actions/upload-artifact@v4
       with:
         name: apk
         path: app/build/outputs/apk/debug/app-debug.apk
         if-no-files-found: error

 release:
   name: Release APK
   needs: apk
   if: github.ref_type == 'tag'
   runs-on: ubuntu-latest
   steps:
     - name: Download APK from build
       uses: actions/download-artifact@v4
       with:
         name: apk
         path: apk
     - name: Publish GitHub release
       uses: softprops/action-gh-release@v2
       with:
         name: New Release ${{ github.ref_name }}
         tag_name: ${{ github.ref_name }}
         files: apk/app-debug.apk
         generate_release_notes: true
